### PR TITLE
Bump to markovify 0.2.0

### PR DESCRIPTION
**Pull request by jsvine**
Compensates for changes in how `markovify.Text` handles the max_overlap settings. This new approach is closer in line with `markovify.Text`'s other settings and allows for more control over output. Apologies for the breaking change.

### CODE REVIEW

**Comment by jsvine** [comment]
p.s., @Deimos, such a fun project. :+1:

**Comment by Deimos** [comment]
Oh thanks @jsvine, I actually didn't even know that you were aware of SubredditSimulator (I probably should have told you, since it's basically powered by your library). Thanks for doing the pull req here, and for markovify in general, I might send some pulls in for it at some point as well.

**Comment by Deimos** [comment]
Merged https://github.com/Deimos/SubredditSimulator/commit/8587ec90c7cf85f877aaa84231121e68a39cbe9a

**Comment by jsvine** [comment]
No worries at all, and sounds great. :tada:

**Pull request closed without merging**
